# SPDX-License-Identifier: GPL-2.0
#ccflags-y += -D__CHECK_ENDIAN__
CFLAGS_trace.o := -I$(src)

obj-$(CONFIG_SCHED_WALT) += walt.o boost.o sched_avg.o qc_vas.o core_ctl.o trace.o
obj-$(CONFIG_CPU_FREQ) += cpu-boost.o
